### ISSUE TITLE
Invoice not getting paid 

### ISSUE THREAD

**Issue by Aakash-divi** [razorpay/razorpay-whmcs#74]
Dear team,

Whenever customer done payment invoice still showing unpaid so pls fix this issue.

**Comment by rohitcbr** [comment]
@Aakash-divi is the issue fixed with the latest version of razorpay-whmcs?

**Comment by Aakash-divi** [comment]
Issue is still same not 100% but better then previous version.
